---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibizservicerunner-provider
  labels:
    app: ibizservicerunner-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibizservicerunner-provider
  template:
    metadata:
      labels:
        app: ibizservicerunner-provider
    spec:
      imagePullSecrets:
      - name: aly-shanghai
      containers:
      - name: ibizservicerunner-provider
        image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibizservicerunner-provider:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30050
        env:
        - name: SPRING_CLOUD_NACOS_DISCOVERY_IP
          value: "172.16.240.140"      
        - name: SERVER_PORT
          value: "30050"
        - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR
          value: "172.16.240.140:8848"
        - name: SPRING_REDIS_HOST
          value: "127.0.0.1"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: SPRING_REDIS_DATABASE
          value: "0"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:master"
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_DEFAULTSCHEMA
          value: "root"
        - name: NACOS
          value: "172.16.240.140:8848"      

---
apiVersion: v1
kind: Service
metadata:
  name: ibizservicerunner-provider
  labels:
    app: ibizservicerunner-provider
spec:
  type: NodePort
  ports:
  - name: http
    port: 30050
    targetPort: 30050
    nodePort: 30050
    protocol: TCP
  selector:
    app: ibizservicerunner-provider

